{
 "title": "Sentio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {
     "query": "query_result(docker_container_cpu_usage_percent_yhat{container_name=~\".+\"})"
    }
   },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(docker_container_cpu_usage_percent{container_name=~\"^$container_name\"}) by (container_name)",
     "legendFormat": "{{container_name}} - Actual"
    },
    {
     "expr": "docker_container_cpu_usage_percent_yhat{container_name=~\"^$container_name\"}",
     "legendFormat": "{{container_name}} - Predicted"
    },
    {
     "expr": "docker_container_cpu_usage_percent_yhat_lower{container_name=~\"^$container_name\"}",
     "legendFormat": "{{container_name}} - Lower"
    },
    {
     "expr": "docker_container_cpu_usage_percent_yhat_upper{container_name=~\"^$container_name\"}",
     "legendFormat": "{{container_name}} - Upper"
    }
   ]
  },
  {
   "title": "Difference in Actual and Prediction",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "abs(avg(docker_container_cpu_usage_percent{container_name=~\"^$container_name\"}) by (container_name) - avg(docker_container_cpu_usage_percent_yhat{container_name=~\"^$container_name\"}) by (container_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Range over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(docker_container_cpu_usage_percent_yhat_upper{container_name=~\"^$container_name\"}) by (container_name) - avg(docker_container_cpu_usage_percent_yhat_lower{container_name=~\"^$container_name\"}) by (container_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}