{
 "title": "Sentio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": {
     "query": "query_result(sqlserver_server_properties_cpu_count{sql_instance=~\".+\"})"
    }
   },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sqlserver_cpu_sqlserver_process_cpu{sql_instance=~\"^$sql_instance\"}) by (sql_instance)",
     "legendFormat": "{{sql_instance}} - Actual"
    },
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu_yhat{sql_instance=~\"^$sql_instance\"}",
     "legendFormat": "{{sql_instance}} - Predicted"
    },
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu_yhat_lower{sql_instance=~\"^$sql_instance\"}",
     "legendFormat": "{{sql_instance}} - Lower"
    },
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu_yhat_upper{sql_instance=~\"^$sql_instance\"}",
     "legendFormat": "{{sql_instance}} - Upper"
    }
   ]
  },
  {
   "title": "Difference in Actual and Prediction",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "abs(avg(sqlserver_cpu_sqlserver_process_cpu{sql_instance=~\"^$sql_instance\"}) by (sql_instance) - avg(sqlserver_cpu_sqlserver_process_cpu_yhat{sql_instance=~\"^$sql_instance\"}) by (sql_instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Range over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(sqlserver_cpu_sqlserver_process_cpu_yhat_upper{sql_instance=~\"^$sql_instance\"}) by (sql_instance) - avg(sqlserver_cpu_sqlserver_process_cpu_yhat_lower{sql_instance=~\"^$sql_instance\"}) by (sql_instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}