global:
  scrape_interval:     30s
  scrape_timeout:      15s
scrape_configs:
  - job_name: telegraf
    metrics_path: /metrics
    static_configs:
      - targets: ["telegraf:9273"]
  - job_name: Sentio
    scrape_interval:     30s
    scrape_timeout:      30s
    metrics_path: /metrics
    static_configs:
      - targets: ["sentio:8000"]
